### ISSUE TITLE
Create Interesting Stories/Facts from the aid data

### ISSUE THREAD

**Issue by michaelgreis** [maevyn11/dsforthepeople#110]
Write SQL statement showing some interesting facts about aid money flows. Top 10 aid contributors, how aid flows have changed through the years, etc. for the Blog post next week.

**Comment by marksmastrangelo** [comment]
Hey @michaelgreis ,

Attached you will find two docs:

1. Mayven SQL - Aid Date 7.29.txt - contains all of my queries (so far) and results. I wrote all these queries in Sublime Text, but Github doesn't accept .sql. What is the best way to share these types of queries and such? Want to make sure we're all using the same process to cut down on nuances.

2. Donor Countries - Excel filed zipped. I am having trouble creating the report as something I can easily manipulate in excel. I can edit the manipulate it manually, but am curious if there is an easier way to have it spit it out to begin with. 

Overall, this was a really great first exercise to test myself & my recent step back into SQL. I am going to connect with a coworker that uses it daily to see if he can give me a few tips and help dive deeper than my initial take. Unfortunately, I'm getting kicked out of the coffee shop I'm at right now so calling it a night. 

That being said, let me know if you want to hop on the phone at some point this weekend (morning works best as I received free Lolla tickets). Again, most of the queries are pretty basic at the moment, but I think these are some good thought starters and I have a list of ideas I'd like to tackle next within the data after working with my coworker for some deeper help. 

-Mark

[Donor Countries.xlsx.zip](https://github.com/maevyn11/dsforthepeople/files/391718/Donor.Countries.xlsx.zip)


[Mayven SQL - Aid Data 7.29.txt](https://github.com/maevyn11/dsforthepeople/files/391712/Mayven.SQL.-.Aid.Data.7.29.txt)

**Comment by michaelgreis** [comment]
@marksmastrangelo 

Looks good! Definitely some useful stuff in there. If you would like to talk with me or Michelle feel free! Both of us have a lot of experience with SQL and can provide pointers. If you would like to set up  facetime or something tomorrow or this week, let me know.
