### ISSUE TITLE
Refactor nytimes for loop to correct page numbering logic

### ISSUE THREAD

**Issue by maevyn11** [maevyn11/dsforthepeople#32]
The loop as is only traverses urls that include page=n in the results but the page=1 page is actually the second page of results for each of our queries. In other words, the nytimes site is 0 indexing their search urls and nytimes.py is starting the index at 1, missing the first article. Fixing it so that the first time the date changes the url excluding page=n is used will get better data. Can combine this with the loop optimization to change page_number < 100 to page_number < num_hits % 10, as there are 10 results per page. (Or is that %10 + 1)

**Comment by michaelgreis** [comment]
Bug needs to be fixed if we are designing crawler for production.
