### ISSUE TITLE
Relational Table with country -> region -> city etc.. needed to refine ETL search

### ISSUE THREAD

**Issue by aistein** [maevyn11/dsforthepeople#49]
The first iteration of the ETL algorithm will not search for granular terms like city, state, or town names.  However, this will ultimately be necessary to properly process the NYTimes articles and how they will be related to aid data.

Secondary iterations of the ETL algorithm (after it has been refined to the point where it reads in and writes out as quickly as possible using multithreading and efficient load and search) will use this relational table.

**Comment by michaelgreis** [comment]
Have country table. City not needed.
