### ISSUE TITLE
Write Python Per Article Location Count Code

### ISSUE THREAD

**Issue by maevyn11** [maevyn11/dsforthepeople#9]

**Comment by maevyn11** [comment]
Estimate the NYTimes data will be 10-15GB for the raw text, so a performant program that can count occurrences of specific strings in a large amount of text will be necessary.

**Comment by maevyn11** [comment]
Initial Design:
Retrieves List of Distinct Countries from aid_data table, compares list to each article's text, returns names of any matched places and inserts alongside article metadata. 
Multiple string mentions stored as array like type in postgres. 

provides great flexiblity for analysis, filter by date of mention, filter by article type, filter by article keywords, etc.

**Comment by maevyn11** [comment]
http://stackoverflow.com/questions/15190580/python-search-one-million-strings-in-a-file-and-count-occurrences-of-each-string

**Comment by maevyn11** [comment]
Might be overcomplicating it. Could also do it with a simple bash grep with a for loop as grep is extremely performant. Will test with some sample data to get an idea of viability.

**Comment by maevyn11** [comment]
grep -Eo 'DEBUG|parse' *

**Comment by aistein** [comment]
Naming conventions need to meet ISO standards

**Comment by aistein** [comment]
Multi-threading example for this problem:

http://stackoverflow.com/questions/7776293/read-txt-file-with-multi-threaded-in-python

**Comment by aistein** [comment]
Profile the performance of the algorithm with python profile library:

https://docs.python.org/2/library/profile.html
